workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1  # استخدام Mac Mini M1 للبناء
    max_build_duration: 60
    environment:
      flutter: stable  # استخدم أحدث إصدار مستقر من Flutter
      xcode: latest  # استخدم أحدث إصدار من Xcode
      cocoapods: default  # تثبيت CocoaPods
      vars:
        BUNDLE_ID: "com.example.rheal"  # استبدل بمعرف حزمتك الفعلي
        #APPLE_DEVELOPER_TEAM_ID: "YOUR_TEAM_ID"  # ضع معرف فريق Apple Developer
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --no-codesign
      - name: Archive app
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace="ios/Runner.xcworkspace" --scheme="Runner"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "se.abdalrhmanahmed@gmail.com"

