export FLUTTER_ROOT="$HOME/flutter"
export FLUTTER_APPLICATION_PATH="$(pwd)"
export FLUTTER_TARGET="lib/main.dart"
export FLUTTER_BUILD_DIR="build"
export SYMROOT="${SOURCE_ROOT}/../build/ios"
export FLUTTER_FRAMEWORK_DIR="$FLUTTER_ROOT/bin/cache/artifacts/engine/ios"
export OTHER_LDFLAGS="$(inherited) -framework Flutter"
