# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# Ignore all warnings from CocoaPods
inhibit_all_warnings!

# Add Flutter dependencies
flutter_root = File.expand_path('..', __dir__)
load File.join(flutter_root, 'flutter', 'tools', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
