require File.expand_path('../flutter_export_environment.sh', __FILE__)

platform :ios, '14.0'

target 'Runner' do
  use_frameworks!

  # تثبيت جميع الـ Pods الخاصة بـ Flutter
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
